Add multipart/form-data JSON part support
braintree/braintreehttp_python pull request #2
Opened 2018-03-28 22:51 UTC by bluk

* Add GIF mimetype support
* Add `FormPart` to allow serialization of individual parts with custom headers
* Change `Encoder` to take a list of serializers
* Change the order to ensure that file parts are last

2018-03-29 20:32 UTC, sdcoffey requested changes
Looks good, just gotta fix the travis build.

2018-03-29 20:32 UTC, sdcoffey commented on tests/encoder_test.py
> +from braintreehttp.serializers import FormPart
Probably can bump this down onto the next import statement

2018-03-29 20:32 UTC, sdcoffey commented on tests/__init__.py
> +from tests.serializers.form_part_test import *
This line is causing problems [in travis](https://travis-ci.org/braintree/braintreehttp_python/jobs/359607711)

2018-04-10 18:48 UTC, bluk commented
@sdcoffey Can you please take another pass? Thanks.

2018-04-10 20:29 UTC, sdcoffey approved these changes
Looks good!

2018-04-10 20:31 UTC, merged